### Importar librer√≠as

In [1]:
import pandas as pd 
import numpy as np

### Crear diccionario y DataFrame

In [10]:
dict = {'Col1':[1,2,3,np.nan],
 'Col2':[4,np.nan,6,7],
 'Col3':['a','b','c',None]}

In [11]:
dict

{'Col1': [1, 2, 3, nan], 'Col2': [4, nan, 6, 7], 'Col3': ['a', 'b', 'c', None]}

In [3]:
df = pd.DataFrame(dict)

In [12]:
df

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

### Ver valores nulos

In [13]:
df.isnull()

    Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [7]:
df.isnull()*1

   Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

### Llenar valores nulos

In [15]:
df.fillna('Missing')#Cada que encuentre un valor nulo, se visualiza la palabra missing

      Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [16]:
df.fillna(df.mean())#Se llenan los valores con la media

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

   Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

### Interpolar

In [18]:
df.interpolate() #Hace la interpolacion ed la serie

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

### Borrar valores nulos

In [19]:
df.dropna()

   Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c